[WinEventLog:Security]
SHOULD_LINEMERGE = false
EXTRACT-user = Hesap\s+Ad[ıi]\s*:\s*\S+[^\n]*\n.*?Hesap\s+Ad[ıi]\s*:\s*(?<user>\S+)
EXTRACT-domain = Hesap\s+Etki\s+Alan[ıi]\s*:\s*\S+[^\n]*\n.*?Hesap\s+Etki\s+Alan[ıi]\s*:\s*(?<domain>\S+)
EXTRACT-src_ip = Kaynak\s+A[ğg]\s+Adresi\s*:\s*(?<src_ip>\S+)
EXTRACT-logon_type = Oturum\s+A[çc]ma\s+T[üu]r[üu]\s*:\s*(?<logon_type>\S+)
EXTRACT-auth_package = Kimlik\s+Do[ğg]rulama\s+Paketi\s*:\s*(?<auth_package>\S+)
EXTRACT-logon_process = Oturum\s+A[çc]ma\s+[İi][şs]lemi\s*:\s*(?<logon_process>\S+)
EXTRACT-src_port = Kaynak\s+Ba[ğg]lant[ıi]\s+Noktas[ıi]\s*:\s*(?<src_port>\S+)
