[winlog_normalize_security]
REGEX = .
DEST_KEY = MetaData:Host
FORMAT = host::$1

[winlog_field_user]
SOURCE_KEY = Hesap Adı
DEST_KEY = user
REGEX = (.+)
FORMAT = $1

[winlog_field_src_ip]
SOURCE_KEY = Kaynak Ağ Adresi
DEST_KEY = src_ip
REGEX = (.+)
FORMAT = $1

[winlog_field_domain]
SOURCE_KEY = Hesap Etki Alanı
DEST_KEY = domain
REGEX = (.+)
FORMAT = $1

[winlog_field_logon_type]
SOURCE_KEY = Oturum Açma Türü
DEST_KEY = logon_type
REGEX = (.+)
FORMAT = $1

[winlog_field_logon_process]
SOURCE_KEY = Oturum Açma İşlemi
DEST_KEY = logon_process
REGEX = (.+)
FORMAT = $1

[winlog_field_auth_package]
SOURCE_KEY = Kimlik Doğrulama Paketi
DEST_KEY = auth_package
REGEX = (.+)
FORMAT = $1

[winlog_field_privileges]
SOURCE_KEY = Ayrıcalıklar
DEST_KEY = privileges
REGEX = (.+)
FORMAT = $1

[winlog_field_workstation]
SOURCE_KEY = Kaynak Bağlantı Noktası
DEST_KEY = src_port
REGEX = (.+)
FORMAT = $1
